"""init schema

Revision ID: 1d6bb24d1cea
Revises: 
Create Date: 2026-09-11 13:15:48.394589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6bb24d1cea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_no', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('mgmt_ip', sa.String(), nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('rack', sa.String(), nullable=False),
    sa.Column('rack_unit', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('serial_no', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('use_user', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key_type', sa.String(length=16), nullable=False),
    sa.Column('key_value', sa.String(length=255), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_fail_at', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_type', 'key_value', name='uq_login_attempts')
    )
    op.create_index(op.f('ix_login_attempts_key_type'), 'login_attempts', ['key_type'], unique=False)
    op.create_index(op.f('ix_login_attempts_key_value'), 'login_attempts', ['key_value'], unique=False)
    op.create_table('topologies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_ports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('connected_to', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_ports_device_id'), 'device_ports', ['device_id'], unique=False)
    op.create_table('topology_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topology_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_edges_source'), 'topology_edges', ['source'], unique=False)
    op.create_index(op.f('ix_topology_edges_target'), 'topology_edges', ['target'], unique=False)
    op.create_index(op.f('ix_topology_edges_topology_id'), 'topology_edges', ['topology_id'], unique=False)
    op.create_table('topology_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topology_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_nodes_device_id'), 'topology_nodes', ['device_id'], unique=False)
    op.create_index(op.f('ix_topology_nodes_topology_id'), 'topology_nodes', ['topology_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_nodes_topology_id'), table_name='topology_nodes')
    op.drop_index(op.f('ix_topology_nodes_device_id'), table_name='topology_nodes')
    op.drop_table('topology_nodes')
    op.drop_index(op.f('ix_topology_edges_topology_id'), table_name='topology_edges')
    op.drop_index(op.f('ix_topology_edges_target'), table_name='topology_edges')
    op.drop_index(op.f('ix_topology_edges_source'), table_name='topology_edges')
    op.drop_table('topology_edges')
    op.drop_index(op.f('ix_device_ports_device_id'), table_name='device_ports')
    op.drop_table('device_ports')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('topologies')
    op.drop_index(op.f('ix_login_attempts_key_value'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_key_type'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
